Fix xPlayer.hasWeapon + xPlayer.getWeapon
TigoDevelopment/redm_extended pull request #4
Opened 2020-05-21 02:48 UTC by ChainTastic

2020-05-21 13:58 UTC, ThymonA requested changes

2020-05-21 13:58 UTC, TigoDevelopment commented on server/objects/player.lua
> +			for k,v in ipairs(RDX.Players[u].loadout) do
Please change this to `pairs` instead of `ipairs`

2020-05-21 16:05 UTC, ChainTastic commented
`RDX.Players[u].getWeapon = function(weaponName)
			for loadoutIndex, weapon in pairs(RDX.Players[u].loadout) do
				if weapon.name == weaponName then
					return loadoutIndex, weapon
				end
			end
		end` would you prefer that format ?

2020-05-22 06:19 UTC, ThymonA approved these changes

2020-05-22 06:20 UTC, merged

2020-05-22 06:20 UTC, TigoDevelopment commented
@ChainTastic Thanks for fixing this issue